/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cs318_finalproject_buynevercry;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Nisha
 */
public class GUICreateAccount extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUICreateAccount.class.getName());

    /**
     * Creates new form GUICreateAccount
     */
    public GUICreateAccount() {
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 255));
        createTable();
        Image icon = new ImageIcon(getClass().getResource("/images/appicon_normal.png")).getImage();
        setIconImage(icon);
    }
    public static void createTable() {
        try {
            Class.forName("org.sqlite.JDBC");
            Connection con = DriverManager.getConnection("jdbc:sqlite:buynevercry.db");
            Statement stmt = con.createStatement();
            String sql = "CREATE TABLE IF NOT EXISTS users (" +
                         "id INTEGER PRIMARY KEY AUTOINCREMENT," +
                         "username TEXT NOT NULL," +
                         "email TEXT NOT NULL UNIQUE," +
                         "password TEXT NOT NULL," +
                         "yearly_salary REAL)";
            stmt.execute(sql);
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new com.mycompany.cs318_finalproject_buynevercry.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        roundedPanel2 = new com.mycompany.cs318_finalproject_buynevercry.RoundedPanel();
        jLabel2 = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        roundedPanel6 = new com.mycompany.cs318_finalproject_buynevercry.RoundedPanel();
        emailtxt = new javax.swing.JTextField();
        pwdlabel = new javax.swing.JLabel();
        roundedPanel9 = new com.mycompany.cs318_finalproject_buynevercry.RoundedPanel();
        pwdtxt = new javax.swing.JPasswordField();
        userlabel = new javax.swing.JLabel();
        roundedPanel10 = new com.mycompany.cs318_finalproject_buynevercry.RoundedPanel();
        usertxt = new javax.swing.JTextField();
        salarylabel = new javax.swing.JLabel();
        roundedPanel11 = new com.mycompany.cs318_finalproject_buynevercry.RoundedPanel();
        salarytxt = new javax.swing.JTextField();
        signinbtn = new com.mycompany.cs318_finalproject_buynevercry.RoundedPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cpwdlabel = new javax.swing.JLabel();
        roundedPanel12 = new com.mycompany.cs318_finalproject_buynevercry.RoundedPanel();
        confirmPwdTxt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Account");

        roundedPanel1.setImageCover(true);
        roundedPanel1.setImageIcon(new javax.swing.ImageIcon(getClass().getResource("/images/appicon_normal.png"))); // NOI18N
        roundedPanel1.setPreferredSize(new java.awt.Dimension(342, 250));

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(12, 20, 33));
        jLabel1.setText("Create your Account");

        roundedPanel2.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel2.setForeground(new java.awt.Color(255, 255, 255));
        roundedPanel2.setBorderColor(new java.awt.Color(255, 255, 255));
        roundedPanel2.setCornerRadius(0);
        roundedPanel2.setImageCover(true);
        roundedPanel2.setImageIcon(new javax.swing.ImageIcon(getClass().getResource("/images/waving-hand-sign_22.png"))); // NOI18N
        roundedPanel2.setPreferredSize(new java.awt.Dimension(30, 0));

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Inter 18pt", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(49, 57, 87));
        jLabel2.setText("To continue to Buynevercry services");

        emaillabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        emaillabel.setForeground(new java.awt.Color(12, 20, 33));
        emaillabel.setText("Email");

        roundedPanel6.setBorderColor(new java.awt.Color(212, 215, 227));
        roundedPanel6.setCornerRadius(8);
        roundedPanel6.setPanelColor(new java.awt.Color(243, 247, 251));
        roundedPanel6.setPreferredSize(new java.awt.Dimension(342, 42));

        emailtxt.setBackground(new java.awt.Color(243, 247, 251));
        emailtxt.setFont(new java.awt.Font("Inter 18pt", 0, 14)); // NOI18N
        emailtxt.setBorder(null);
        emailtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailtxtFocusLost(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel6Layout = new javax.swing.GroupLayout(roundedPanel6);
        roundedPanel6.setLayout(roundedPanel6Layout);
        roundedPanel6Layout.setHorizontalGroup(
            roundedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        roundedPanel6Layout.setVerticalGroup(
            roundedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(emailtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        pwdlabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        pwdlabel.setForeground(new java.awt.Color(12, 20, 33));
        pwdlabel.setText("Password");

        roundedPanel9.setBorderColor(new java.awt.Color(212, 215, 227));
        roundedPanel9.setCornerRadius(8);
        roundedPanel9.setPanelColor(new java.awt.Color(243, 247, 251));
        roundedPanel9.setPreferredSize(new java.awt.Dimension(342, 42));

        pwdtxt.setBackground(new java.awt.Color(243, 247, 251));
        pwdtxt.setBorder(null);
        pwdtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdtxtFocusLost(evt);
            }
        });
        pwdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdtxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel9Layout = new javax.swing.GroupLayout(roundedPanel9);
        roundedPanel9.setLayout(roundedPanel9Layout);
        roundedPanel9Layout.setHorizontalGroup(
            roundedPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pwdtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel9Layout.setVerticalGroup(
            roundedPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pwdtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        userlabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        userlabel.setForeground(new java.awt.Color(12, 20, 33));
        userlabel.setText("Username");

        roundedPanel10.setBorderColor(new java.awt.Color(212, 215, 227));
        roundedPanel10.setCornerRadius(8);
        roundedPanel10.setPanelColor(new java.awt.Color(243, 247, 251));
        roundedPanel10.setPreferredSize(new java.awt.Dimension(342, 42));

        usertxt.setBackground(new java.awt.Color(243, 247, 251));
        usertxt.setFont(new java.awt.Font("Inter 18pt", 0, 14)); // NOI18N
        usertxt.setToolTipText("");
        usertxt.setBorder(null);
        usertxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usertxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usertxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usertxtFocusLost(evt);
            }
        });
        usertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel10Layout = new javax.swing.GroupLayout(roundedPanel10);
        roundedPanel10.setLayout(roundedPanel10Layout);
        roundedPanel10Layout.setHorizontalGroup(
            roundedPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(usertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        roundedPanel10Layout.setVerticalGroup(
            roundedPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usertxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        salarylabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        salarylabel.setForeground(new java.awt.Color(12, 20, 33));
        salarylabel.setText("Yearly Salary");

        roundedPanel11.setBorderColor(new java.awt.Color(212, 215, 227));
        roundedPanel11.setCornerRadius(8);
        roundedPanel11.setPanelColor(new java.awt.Color(243, 247, 251));
        roundedPanel11.setPreferredSize(new java.awt.Dimension(342, 42));

        salarytxt.setBackground(new java.awt.Color(243, 247, 251));
        salarytxt.setFont(new java.awt.Font("Inter 18pt", 0, 14)); // NOI18N
        salarytxt.setBorder(null);
        salarytxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                salarytxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                salarytxtFocusLost(evt);
            }
        });
        salarytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarytxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel11Layout = new javax.swing.GroupLayout(roundedPanel11);
        roundedPanel11.setLayout(roundedPanel11Layout);
        roundedPanel11Layout.setHorizontalGroup(
            roundedPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(salarytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        roundedPanel11Layout.setVerticalGroup(
            roundedPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salarytxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        signinbtn.setBackground(new java.awt.Color(22, 45, 58));
        signinbtn.setBorderColor(new java.awt.Color(22, 45, 58));
        signinbtn.setPanelColor(new java.awt.Color(22, 45, 58));
        signinbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinbtnMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Inter 18pt", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Sign up");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout signinbtnLayout = new javax.swing.GroupLayout(signinbtn);
        signinbtn.setLayout(signinbtnLayout);
        signinbtnLayout.setHorizontalGroup(
            signinbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signinbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );
        signinbtnLayout.setVerticalGroup(
            signinbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signinbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Inter 18pt", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(149, 156, 182));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Powered By Buynevercry");

        cpwdlabel.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        cpwdlabel.setForeground(new java.awt.Color(12, 20, 33));
        cpwdlabel.setText("Confirm Password");

        roundedPanel12.setBorderColor(new java.awt.Color(212, 215, 227));
        roundedPanel12.setCornerRadius(8);
        roundedPanel12.setPanelColor(new java.awt.Color(243, 247, 251));
        roundedPanel12.setPreferredSize(new java.awt.Dimension(342, 42));

        confirmPwdTxt.setBackground(new java.awt.Color(243, 247, 251));
        confirmPwdTxt.setBorder(null);
        confirmPwdTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPwdTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmPwdTxtFocusLost(evt);
            }
        });
        confirmPwdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPwdTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel12Layout = new javax.swing.GroupLayout(roundedPanel12);
        roundedPanel12.setLayout(roundedPanel12Layout);
        roundedPanel12Layout.setHorizontalGroup(
            roundedPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel12Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(confirmPwdTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel12Layout.setVerticalGroup(
            roundedPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmPwdTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roundedPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpwdlabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(salarylabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emaillabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signinbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundedPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundedPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwdlabel)
                            .addComponent(roundedPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundedPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundedPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(userlabel)
                .addGap(8, 8, 8)
                .addComponent(roundedPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emaillabel)
                .addGap(8, 8, 8)
                .addComponent(roundedPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(pwdlabel)
                .addGap(8, 8, 8)
                .addComponent(roundedPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpwdlabel)
                .addGap(8, 8, 8)
                .addComponent(roundedPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salarylabel)
                .addGap(8, 8, 8)
                .addComponent(roundedPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(signinbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertxtActionPerformed

    private void salarytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarytxtActionPerformed

    private void signinbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinbtnMouseClicked
        String username = usertxt.getText();
        String email = emailtxt.getText();
        String password = new String(pwdtxt.getPassword());
        

        String confirmPassword = new String(confirmPwdTxt.getPassword()); 

        String salaryStr = salarytxt.getText();

        if (username.isEmpty() || email.isEmpty() || password.isEmpty() || salaryStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields.", "Incomplete Info", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String emailPattern = "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,}$";
        if (!email.matches(emailPattern)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address (e.g., user@example.com).", "Invalid Email", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (password.length() < 6) {
            JOptionPane.showMessageDialog(this, "Password must be at least 6 characters long.", "Weak Password", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match. Please try again.", "Password Mismatch", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Connection con = null;
        try {
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:buynevercry.db");

            String sql = "INSERT INTO users (username, email, password, yearly_salary) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, email);
            pst.setString(3, password);
            
            double salary = 0;
            
            try {
                salary = Double.parseDouble(salaryStr);
                pst.setDouble(4, salary);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Yearly Salary must be a valid number.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int row = pst.executeUpdate();

            if (row > 0) {
                String sqlSettings = "INSERT INTO user_settings " +
                                     "(email, salary, days_per_week, hours_per_day, investment_return, currency) " +
                                     "VALUES (?, ?, 5, 8, 5.0, 'THB (฿)')";

                try (PreparedStatement pstSet = con.prepareStatement(sqlSettings)) {
                    pstSet.setString(1, email);
                    pstSet.setDouble(2, salary);
                    pstSet.executeUpdate();
                } catch (SQLException ex) {
                    System.out.println("Init Settings Error: " + ex.getMessage());
                }
                // ---------------------------------------------

                JOptionPane.showMessageDialog(this, "Account Created Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
            

        } catch (Exception e) {
            if (e.getMessage().contains("UNIQUE constraint failed")) {
                JOptionPane.showMessageDialog(this, "This email is already registered.", "Registration Failed", JOptionPane.ERROR_MESSAGE);
            } else {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } finally {
            try { if (con != null) con.close(); } catch (Exception ex) {}
        }
    }//GEN-LAST:event_signinbtnMouseClicked

    private void usertxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usertxtFocusGained

    }//GEN-LAST:event_usertxtFocusGained

    private void usertxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usertxtFocusLost

    }//GEN-LAST:event_usertxtFocusLost

    private void emailtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailtxtFocusGained
  
    }//GEN-LAST:event_emailtxtFocusGained

    private void emailtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailtxtFocusLost

    }//GEN-LAST:event_emailtxtFocusLost

    private void pwdtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdtxtFocusGained

    }//GEN-LAST:event_pwdtxtFocusGained

    private void pwdtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdtxtFocusLost

    }//GEN-LAST:event_pwdtxtFocusLost

    private void salarytxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salarytxtFocusGained

    }//GEN-LAST:event_salarytxtFocusGained

    private void salarytxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salarytxtFocusLost

    }//GEN-LAST:event_salarytxtFocusLost

    private void pwdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdtxtActionPerformed

    private void confirmPwdTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPwdTxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPwdTxtFocusGained

    private void confirmPwdTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPwdTxtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPwdTxtFocusLost

    private void confirmPwdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPwdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPwdTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUICreateAccount().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPwdTxt;
    private javax.swing.JLabel cpwdlabel;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel pwdlabel;
    private javax.swing.JPasswordField pwdtxt;
    private com.mycompany.cs318_finalproject_buynevercry.RoundedPanel roundedPanel1;
    private com.mycompany.cs318_finalproject_buynevercry.RoundedPanel roundedPanel10;
    private com.mycompany.cs318_finalproject_buynevercry.RoundedPanel roundedPanel11;
    private com.mycompany.cs318_finalproject_buynevercry.RoundedPanel roundedPanel12;
    private com.mycompany.cs318_finalproject_buynevercry.RoundedPanel roundedPanel2;
    private com.mycompany.cs318_finalproject_buynevercry.RoundedPanel roundedPanel6;
    private com.mycompany.cs318_finalproject_buynevercry.RoundedPanel roundedPanel9;
    private javax.swing.JLabel salarylabel;
    private javax.swing.JTextField salarytxt;
    private com.mycompany.cs318_finalproject_buynevercry.RoundedPanel signinbtn;
    private javax.swing.JLabel userlabel;
    private javax.swing.JTextField usertxt;
    // End of variables declaration//GEN-END:variables
}
